name: ReviewServer
main: Angga7Togk\ReviewServer\Main
version: 1.0.0
api: 4.0.0
author: Angga7Togk
description: ReviewServer

commands:
  review:
    description: "open the review server menu"
    permission: review.command
    aliases: [ratting, issue]
permissions:
  review.command:
    default: true